### ISSUE TITLE
Listview Footer Crash

### ISSUE THREAD

**Issue by Jilberta** [nhaarman/ListViewAnimations#342]
When you add footer to DynamicListView and enable DragAndDrop and enable SwipeToDismiss, footer is also swipable and throws following error:

 java.lang.IllegalStateException: User must be touching the DynamicListView!
 at com.nhaarman.listviewanimations.itemmanipulation.dragdrop.DragAndDropHandler.startDragging(DragAndDropHandler.java:217)
            at com.nhaarman.listviewanimations.itemmanipulation.DynamicListView.startDragging(DynamicListView.java:432)

**Comment by Jilberta** [comment]
My WorkAround at this stage is checking position of the View. Every added footer is considered as the child of the parentView, so my onItemLongClick looks like this:

dynamicListview.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                    if(position < (parent.getCount() - footerViewsCount)) {
                        list.startDragging(position);
                    }
                return true;
            }
        });

**Comment by Topone** [comment]
But, when i add footer and header,it will be error.
