### ISSUE TITLE
Getting Exception Call setAbsListView() on this AnimationAdapter first!

### ISSUE THREAD

**Issue by smraj01** [nhaarman/ListViewAnimations#369]
While i try to run the Dynamic list view i am getting this error. Any Idea...

11-19 01:20:23.382    2276-2276/com.tempapp.myapplication E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.tempapp.myapplication, PID: 2276
    java.lang.IllegalStateException: Call setAbsListView() on this AnimationAdapter first!
            at com.tempapp.myapplication.appearance.AnimationAdapter.getView(AnimationAdapter.java:134)
            at com.tempapp.myapplication.BaseAdapterDecorator.getView(BaseAdapterDecorator.java:125)
            at com.tempapp.myapplication.itemmanipulation.animateaddition.AnimateAdditionAdapter.getView(AnimateAdditionAdapter.java:291)
            at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
            at android.widget.AbsListView.obtainView(AbsListView.java:2344)
            at android.widget.ListView.makeAndAddView(ListView.java:1864)
            at android.widget.ListView.fillDown(ListView.java:698)
            at android.widget.ListView.fillFromTop(ListView.java:759)
            at android.widget.ListView.layoutChildren(ListView.java:1673)
            at android.widget.AbsListView.onLayout(AbsListView.java:2148)
            at android.view.View.layout(View.java:15614)
            at android.view.ViewGroup.layout(ViewGroup.java:4968)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15614)
            at android.view.ViewGroup.layout(ViewGroup.java:4968)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15614)
            at android.view.ViewGroup.layout(ViewGroup.java:4968)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15614)
            at android.view.ViewGroup.layout(ViewGroup.java:4968)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1077)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

Thanks in advance......

**Comment by zishanj** [comment]
You have to call `setAbsListView()` on your Dynamic List View adapter and pass in the list view reference before attaching the adapter to list.
