### ISSUE TITLE
Getting "Adapter should implement Swappable!" even after implementing it.

### ISSUE THREAD

**Issue by anjanibansal** [nhaarman/ListViewAnimations#378]
I've been trying to use the `DynamicListView` for drag n drop functionality. I'm using a custom `RealmBaseAdapter` to populate the listview. My adapter already has `hasStableIds` and `swapItems()` implementation and yet, whenever I run the program, I get the above mentioned `IllegalArgumentException`.  
  
Here is the simplified code:  
  
```
static class MyAdapter extends RealmBaseAdapter<MyItem>
            implements Swappable, ListAdapter {

      @Override
        public boolean hasStableIds() {
            return true;
        }

        @Override
        public void swapItems(int i, int i2) {
//            this.notifyDataSetChanged();
        }
}  

```  
And here's the logcat:  
  
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anjani.myapp/com.anjani.myapp.activity.MyActivity}: java.lang.IllegalArgumentException: Adapter should implement Swappable!
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
         at android.app.ActivityThread.-wrap11(ActivityThread.java)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
         at android.os.Handler.dispatchMessage(Handler.java:102)
         at android.os.Looper.loop(Looper.java:148)
         at android.app.ActivityThread.main(ActivityThread.java:5417)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Adapter should implement Swappable!
	at com.nhaarman.listviewanimations.itemmanipulation.dragdrop.DragAndDropHandler.setAdapterInternal(DragAndDropHandler.java:187)
	at com.nhaarman.listviewanimations.itemmanipulation.dragdrop.DragAndDropHandler.<init>(DragAndDropHandler.java:143)
	at com.nhaarman.listviewanimations.itemmanipulation.dragdrop.DragAndDropHandler.<init>(DragAndDropHandler.java:131)
	at com.nhaarman.listviewanimations.itemmanipulation.DynamicListView.enableDragAndDrop(DynamicListView.java:139)
	at com.anjani.myapp.activity.MyActivity.onStart(MyActivity.java:141)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
	at android.app.Activity.performStart(Activity.java:6268)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
	at android.app.ActivityThread.-wrap11(ActivityThread.java) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loop(Looper.java:148) 
	at android.app.ActivityThread.main(ActivityThread.java:5417) 
	at java.lang.reflect.Method.invoke(Native Method)
```

The activity isn't even launching. The app just crashes right away. Is there anything I'm missing or have done wrong? Please help me out with the issue.

**Comment by anjanibansal** [comment]
Is there anyone out here who can help me?
